config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :organizations, controllers: {
      sessions: 'organizations/sessions',
      registrations: 'organizations/registrations'
  }

  root 'welcome#index'

  get '/welcome_organizations' =>'welcome#index_organizations', as: :welcome_organizations

  get '/town-by-province' => 'location#town_by_province', as: :town_by_province
  get '/provinces-by-region' => 'location#provinces_by_region', as: :provinces_by_region
  get '/s/:id' => 'shortener/shortened_urls#show', as: :short_url
  get '/account-locked' => 'welcome#account_locked', as: :account_locked

  post '/tinymce_assets' => 'posts#tinymce_assets_create'
  post '/contact' => 'welcome#contact', as: :contact

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          post '/images', to: 'users#update_images'
        end
        member do
          get :campaigns
          post '/campaigns/:campaign_id', to: 'users#send_campaign'
        end
        member do
          get :organizations
          get '/organizations/:organization_id', to: 'users#show_organization'
          put '/organizations/:organization_id', to: 'users#follow_organization'
        end
        member do
          get :topics
          get '/topics/:topic_id', to: 'users#show_topic'
          put '/topics/:topic_id', to: 'users#follow_topic'
        end
      end
      resources :organizations do
        member do
          get :campaigns
        end
      end
      resources :campaigns
      resources :topics do
        member do
          get :campaigns
          get :organizations
        end
      end
      scope 'leaderboard' do
        get '/' => 'leaderboard#index', as: :leaderboard
      end
    end
  end

  namespace :blog do
    resources :campaigns, only: [:index, :show]
    resources :posts, only: [:index, :show]
  end

  scope 'dashboard' do
    get '/' => 'welcome#dashboard', as: :dashboard
    resources :campaigns, except: [ :destroy ] do
      collection do
        get '/filter' => 'campaigns#filter'
      end
      member do
        match :crop, via: [:get, :post]
        delete :stop
        get :statistics
      end
    end
    scope 'analytics' do
      get '/follow_trending' => 'welcome#follow_trending', as: :follow_trending
      get '/campaigns' => 'analytics#campaigns_analytics', as: :campaigns_analytics
      get '/campaign/:id' => 'analytics#campaign_analytics_async', as: :campaign_analytics_async
      get '/campaigns_async' => 'analytics#campaigns_analytics_async'
      get '/my-organization' => 'analytics#organization_analytics', as: :organization_analytics
    end
  end

  post '/organizations/:id/upload' => 'organizations#upload', as: :organizations_upload
  match '/organizations/:id/crop' => 'organizations#crop', as: :organizations_crop, via: [:post, :patch]

  get '/stop/:id' => 'stop#show', as: :stop_service
  delete '/stop/:id' => 'stop#destroy'
  put '/stop/:id' => 'stop#unblacklist'

end

app/models/post.rb
class Post < ActiveRecord::Base

  scope :published, -> { where(published: true) }

  has_attached_file :photo, styles: {
      normal: '700x315>',
  }, default_url: '/images/avatar.png',
                    convert_options: {
                        normal: '-gravity center -extent 700x315',
                    }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  validates_presence_of :title, :content, :admin_user_id, :category_id

  belongs_to :admin_user
  belongs_to :category

  has_many :post_images

  has_and_belongs_to_many :tags

  accepts_nested_attributes_for :category, allow_destroy: true
  accepts_nested_attributes_for :tags, allow_destroy: true

  def published_at
    self.created_at.strftime('<span>%d</span> %B %Y')
  end

end

app/controllers/blog/campaigns_controller.rb
class Blog::CampaignsController < ApplicationController
  force_ssl unless Rails.env.development?
  protect_from_forgery except: [:tinymce_assets_create]
  before_filter :set_campaign, only: [:show]
  layout 'application_frontend'

  def index
    @campaigns = Campaign.not_test

    if params[:running].present?
      if params[:running]=="true"
        @campaigns=@campaigns.where('expires_at >= ?', Date.today)
      end
    end

    if params[:organization].present?
      @campaigns = @campaigns.where(organization_id: params[:organization])
      @organization = Organization.find(params[:organization])
    end

    if params[:topic].present?
      @campaigns = @campaigns.includes(:topics).where(topics: { id: params[:topic] })
      @topic = Topic.find params[:topic]
    end

    @campaigns = @campaigns.paginate(page: params[:page], per_page: 5).order('campaigns.created_at DESC')
  end

  def show
  end

  private

  def set_campaign
    @campaign = Campaign.find params[:id]
  end

end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  force_ssl unless Rails.env.development?
  protect_from_forgery except: [:tinymce_assets_create]
  before_filter :set_post, only: [:show]
  layout 'application_frontend'

  def tinymce_assets_create
    p = params.permit(:file, :alt, :hint)
    geometry = Paperclip::Geometry.from_file p[:file]
    image = PostImage.create p

    render json: {
        image: {
            url: image.file.url,
            height: geometry.height.to_i,
            width: geometry.width.to_i
        }
    }, layout: false, content_type: 'text/html'
  end

  def index
    @posts = Post.published

    if params[:category].present?
      @posts = @posts.where(category_id: params[:category])
      @category = Category.find(params[:category])
    end

    if params[:tag].present?
      @posts = @posts.includes(:tags).where(tags: { id: params[:tag] })
      @tag = Tag.find params[:tag]
    end

    @posts = @posts.paginate(page: params[:page], per_page: 5).order('posts.created_at DESC')
  end

  def show
  end

  def create_campaign_post(this_campaign)
    post=Post.new
    post.title=this_campaign.organization.organization_name
    post.content=this_campaign.message + "\n MORE INFO \n" + this_campaign.long_description
    post.admin_user=AdminUser.find(6)
    post.category=Category.find_or_create_by(title: this_campaign.topics[0].name)
    post.published=true
    unless this_campaign.photo_normal.nil?
      post.photo =this_campaign.photo
    end
    post.save
  end

  private

  def set_post
    @post = Post.find params[:id]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  protect_from_forgery except: [:tinymce_assets_create]
  before_filter :set_post, only: [:show]
  layout 'application_frontend'

  def tinymce_assets_create
    p = params.permit(:file, :alt, :hint)
    geometry = Paperclip::Geometry.from_file p[:file]
    image = PostImage.create p

    render json: {
        image: {
            url: image.file.url,
            height: geometry.height.to_i,
            width: geometry.width.to_i
        }
    }, layout: false, content_type: 'text/html'
  end

  def index
    @posts = Post.published

    if params[:category].present?
      @posts = @posts.where(category_id: params[:category])
      @category = Category.find(params[:category])
    end

    if params[:tag].present?
      @posts = @posts.includes(:tags).where(tags: { id: params[:tag] })
      @tag = Tag.find params[:tag]
    end

    @posts = @posts.paginate(page: params[:page], per_page: 5).order('posts.created_at DESC')
  end

  def show
  end

  private

  def set_post
    @post = Post.find params[:id]
  end

end

app/helpers/blog/campaigns_helper.rb
module Blog::CampaignsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/_aside.html.erb
<aside>
  <nav class="nav-a">
    <h3><%= t 'frontend.categories' %></h3>
    <ul>
      <% Category.all.each do |category| %>
          <li><%= link_to raw("#{category.title} <span>#{category.post_count}</span>"), blog_posts_path(category: category.id) %></li>
      <% end %>
    </ul>
  </nav>
  <nav class="nav-a nav-a-new2">
    <h3><%= t 'frontend.tags' %></h3>
    <ul>
      <% Tag.all.each do |tag| %>
          <li><%= link_to tag.title, blog_posts_path(tag: tag.id) %></li>
      <% end %>
    </ul>
  </nav>
</aside>

app/views/blog/posts/index.html.erb
<% title t('frontend.blog') %>

<article id="featured">
  <h2>
    <% if @category %>
      <%= @category.title %>
    <% elsif @tag %>
      <%= @tag.title %>
    <% else %>
      Blog
    <% end %>
  </h2>
</article>

<section id="content">
  <div class="cols-a">
    <div class="news-e">
      <% @posts.each do |post| %>
          <article>
            <header>
              <% if post.photo.exists? %>
                  <figure><%= image_tag post.photo.url(:normal), width: 700, height: 315 %></figure>
              <% end %>

              <h3><%= link_to post.title, blog_post_path(post.id) %></h3>
              <ul>
                <li><a href="javascript:;"><%= image_tag post.admin_user.avatar.url(:thumb_48), width: 40, height: 40 %>
                  <%= t 'frontent.by' %> <%= post.admin_user %></a></li>
                <li><i class="icon-basic" data-icon="x"></i> <%= raw I18n.localize post.created_at, format: '%d %B %Y' %></li>
              </ul>
            </header>
            <%= raw HTML_Truncator.truncate post.content, 50 %>
            <p class="link-a"><%= link_to t('frontend.read_more'), blog_post_path(post.id) %></p>
          </article>
      <% end %>
      <%= will_paginate @posts, next_label: t('frontend.next'), previous_label: t('frontend.previous') %>
    </div>

    <%= render partial: 'aside' %>
  </div>
</section>

app/views/blog/posts/show.html.erb
<% title @post.title %>

<article id="featured">
  <h2>Blog</h2>
</article>

<section id="content" class="cols-a">
  <div class="news-a">
    <article>
      <header>
        <h3><%= @post.title %></h3>
        <ul>
          <li><a href="javascript:;"><%= image_tag @post.admin_user.avatar.url(:thumb_48), width: 40, height: 40 %>
            <%= t 'frontent.by' %> <%= @post.admin_user %></a></li>
          <li><i class="icon-basic" data-icon="x"></i> <%= raw I18n.localize @post.created_at, format: '%d %B %Y' %></li>
        </ul>
      </header>
      <% if @post.photo.exists? %>
          <figure><%= image_tag @post.photo.url(:normal), width: 700, height: 315 %></figure>
    <% end %>
      <p><%= raw @post.content %></p>
    </article>
  </div>

  <%= render partial: 'aside' %>
</section>