config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :organizations, controllers: {
      sessions: 'organizations/sessions',
      registrations: 'organizations/registrations'
  }

  root 'welcome#index'

  get '/welcome_organizations' =>'welcome#index_organizations', as: :welcome_organizations

  get '/town-by-province' => 'location#town_by_province', as: :town_by_province
  get '/provinces-by-region' => 'location#provinces_by_region', as: :provinces_by_region
  get '/s/:id' => 'shortener/shortened_urls#show', as: :short_url
  get '/account-locked' => 'welcome#account_locked', as: :account_locked

  post '/tinymce_assets' => 'posts#tinymce_assets_create'
  post '/contact' => 'welcome#contact', as: :contact

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          post '/images', to: 'users#update_images'
        end
        member do
          get :campaigns
          post '/campaigns/:campaign_id', to: 'users#send_campaign'
        end
        member do
          get :organizations
          get '/organizations/:organization_id', to: 'users#show_organization'
          put '/organizations/:organization_id', to: 'users#follow_organization'
        end
        member do
          get :topics
          get '/topics/:topic_id', to: 'users#show_topic'
          put '/topics/:topic_id', to: 'users#follow_topic'
        end
      end
      resources :organizations do
        member do
          get :campaigns
        end
      end
      resources :campaigns
      resources :topics do
        member do
          get :campaigns
          get :organizations
        end
      end
      scope 'leaderboard' do
        get '/' => 'leaderboard#index', as: :leaderboard
      end
    end
  end

  namespace :blog do
    resources :campaigns, only: [:index, :show]
    resources :posts, only: [:index, :show]
  end

  scope 'dashboard' do
    get '/' => 'welcome#dashboard', as: :dashboard
    resources :campaigns, except: [ :destroy ] do
      collection do
        get '/filter' => 'campaigns#filter'
      end
      member do
        match :crop, via: [:get, :post]
        delete :stop
        get :statistics
      end
    end
    scope 'analytics' do
      get '/follow_trending' => 'welcome#follow_trending', as: :follow_trending
      get '/campaigns' => 'analytics#campaigns_analytics', as: :campaigns_analytics
      get '/campaign/:id' => 'analytics#campaign_analytics_async', as: :campaign_analytics_async
      get '/campaigns_async' => 'analytics#campaigns_analytics_async'
      get '/my-organization' => 'analytics#organization_analytics', as: :organization_analytics
    end
  end

  post '/organizations/:id/upload' => 'organizations#upload', as: :organizations_upload
  match '/organizations/:id/crop' => 'organizations#crop', as: :organizations_crop, via: [:post, :patch]

  get '/stop/:id' => 'stop#show', as: :stop_service
  delete '/stop/:id' => 'stop#destroy'
  put '/stop/:id' => 'stop#unblacklist'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_organization!, only: [:dashboard]

  # GET /
  def index
    render 'welcome/index', layout: 'application_frontend'
  end

  # GET /
  def index_organizations
    render 'welcome/index_organizations', layout: 'application_frontend'
  end

  def dashboard
    @campaigns = current_organization.campaigns.not_expired.order(:created_at => :desc).limit 5
    @analytics = {}
    oa_last = current_organization.organization_analytics.where('organization_analytics.created_at >= ?', Date.today).last

    if oa_last.present?
      @analytics[:topic_followers] = oa_last.global_supporter
      @analytics[:followers] = oa_last.follower
      @analytics[:truster] = oa_last.truster
      @analytics[:sms_range_trusters] = oa_last.sms_range_truster
      @analytics[:sms_range_followers] = oa_last.sms_range_follower
      @analytics[:sms_range_general] = oa_last.sms_range_general
    else
      @analytics[:followers] = 0
      @analytics[:truster] = 0
    end
    campaigns_count = current_organization.campaigns.count
    if campaigns_count > 0
      @analytics[:campaigns] = campaigns_count
      @analytics[:active_campaigns] = current_organization.campaigns.where('campaigns.expires_at >= ?', Date.today).count
      @analytics[:sent_sms] = current_organization.campaigns.joins(:campaign_analytics).where('campaign_analytics.created_at >= ?', Date.today).sum(:sent_sms)
    else
      @analytics[:campaigns] = 0
      @analytics[:active_campaigns] = 0
      @analytics[:sent_sms] = 0
    end

    render 'welcome/dashboard', layout: 'application_dashboard'
  end

  def account_locked
    render 'welcome/account_locked', layout: 'application_login_no_content'
  end

  # POST /contact
  def contact
    p = params[:contact].permit(:name, :email, :message)
    if p[:name].present? and p[:email].present? and p[:message].present?
      ContactMailer.contact_email(p).deliver_now
      render json: { success: true }
    else
      render json: { error: true }
    end
  end

  def follow_trending
    # analytics for the current organization of the lasts 30 days
    oa=current_organization.organization_analytics.where('organization_analytics.created_at >= ?', Date.today - 29.days)
    organization_followers = oa.map { |x| { created_at: x.created_at.to_date, topic_followers: x.global_supporter, followers: x.follower, trusters: x.truster } }
    topic = []
    followers = []
    trusters = []
    ((Date.today - 29.days)..Date.today).each do |date|
      new_date = date.to_time.to_i * 1000

      organization_followers_select = organization_followers.select { |t| t[:created_at] == date }

      organization_topic_follower_n = organization_followers_select.map { |x| x[:topic_followers] }.sum
      topic.push({ x: new_date, y: organization_topic_follower_n })

      organization_follower_n = organization_followers_select.map { |x| x[:followers] }.sum
      followers.push({ x: new_date, y: organization_follower_n })

      organization_truster_n = organization_followers_select.map { |x| x[:trusters] }.sum
      trusters.push({ x: new_date, y: organization_truster_n })
    end

    render json: [
        {
            values: topic,
            key: I18n.t('welcome.dashboard.topic_followers'),
            color: "#ff7f0e"
        },
        {
            values: followers,
            key: I18n.t('welcome.dashboard.followers'),
            color: "#2ca02c"
        },
        {
            values: trusters,
            key: I18n.t('welcome.dashboard.truster'),
            color: "#7777ff"
        }
    ], root: false
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/account_locked.html.erb
<div class="full-height">
  <div class="container-sm-height full-height">
    <div class="row row-sm-height">
      <div class="col-sm-12 col-sm-height col-middle text-center">
        <h1><%= t 'welcome.account_locked.heading' %></h1>
        <p><%= t 'welcome.account_locked.verifying' %></p>
        <%= link_to t('welcome.account_locked.return_to_homepage'), root_path %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/dashboard.html.erb
<% title t('welcome.dashboard.title') %>

<div class="row">
  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default">

      <div class="panel-heading">
        <div class="panel-title"><%= t 'welcome.dashboard.general_statistics' %></div>
      </div>

      <div class="panel-body">
        <table class="table table-75-25">
          <tbody>
            <tr>
              <td><strong><%= t 'welcome.dashboard.topic_followers' %>:</strong></td>
              <td><%= @analytics[:topic_followers] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'welcome.dashboard.followers' %>:</strong></td>
              <td><%= @analytics[:followers] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'welcome.dashboard.truster' %>:</strong></td>
              <td><%= @analytics[:truster] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'welcome.dashboard.campaigns' %>:</strong></td>
              <td><%= @analytics[:campaigns] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'welcome.dashboard.active_campaigns' %>:</strong></td>
              <td><%= @analytics[:active_campaigns] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'welcome.dashboard.sent_sms' %>:</strong></td>
              <td><%= @analytics[:sent_sms] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'analytics.organizations.sms_range_trusters.other' %>:</strong></td>
              <td><%= @analytics[:sms_range_trusters] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'analytics.organizations.sms_range_followers.other' %>:</strong></td>
              <td><%= @analytics[:sms_range_followers] %></td>
            </tr>
            <tr>
              <td><strong><%= t 'analytics.organizations.sms_range_general.other' %>:</strong></td>
              <td><%= @analytics[:sms_range_general] %></td>
            </tr>
          </tbody>
        </table>
      </div>

    </div>
  </div>

  <div class="col-sm-12 col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="panel-title"><%= t 'welcome.dashboard.recent_campaigns' %>
        </div>
      </div>
      <div class="panel-body scrollable">
        <!-- REMOVE THIS WRAPPER IF .scrollable IS NOT USED -->
        <div style="max-height: 515px">

          <table class="table table-hover">

            <thead>
            <tr>
              <th><%= t 'campaigns.message' %></th>
              <th><%= t 'campaigns.expiration_date' %></th>
              <th><%= t 'campaigns.actions' %></th>
            </tr>
            </thead>

            <tbody>
            <% @campaigns.each do |c| %>
                <tr>
                  <td><%= c.message %></td>
                  <td><%= c.expires_at_format %></td>
                  <td>
                    <%= link_to t('campaigns.show'), c %> <br />
                    <%= link_to t('campaigns.edit'), edit_campaign_path(c) %> <br />
                    <%= link_to t('campaigns.stop'), stop_campaign_path(c), method: :delete %>
                  </td>
                </tr>
            <% end %>
            </tbody>

          </table>

        </div>
      </div>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel panel-default">

      <div class="panel-heading">
        <div class="panel-title"><%= t 'welcome.dashboard.like_trending' %></div>
      </div>

      <div class="panel-body full-height" style="min-height: 300px;">
        <div id="nvd3" class="line-chart"
            data-area-color="master"
            data-points="true"
            data-url="follow_trending">
          <svg style="height: 500px;"></svg>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/welcome/index_old.html.erb
<div class="bg-pic">
  <!-- START Background Pic-->
  <%= image_tag 'new-york-city-buildings-sunrise-morning-hd-wallpaper.jpg', class: 'lazy' %>
  <!-- END Background Pic-->
  <!-- START Background Caption-->

  <!-- END Background Caption-->
</div>

<div class="login-container bg-white">
  <div class="p-l-50 m-l-20 p-r-50 m-r-20 p-t-50 m-t-30 sm-p-l-15 sm-p-r-15 sm-p-t-40">
    <img src="<%= image_path 'logo_website_dark.png' %>" alt="logo" data-src="<%= image_path 'logo_website_dark.png' %>" data-src-retina="<%= image_path 'logo_website_dark.png' %>" width="78" height="22">
    <p class="p-t-35"><%= t 'welcome.index.sign_in' %></p>
    <!-- START Login Form -->
    <%= form_for(:organization, :url => session_path(:organization), html: { id: 'form-login', class: 'p-t-15 m-b-15', role: 'form' }) do |f| %>
      <!-- START Form Control-->
      <div class="form-group form-group-default">
        <%= f.label :email %>
        <div class="controls">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Email', required: 'required' %>
        </div>
      </div>
      <!-- END Form Control-->
      <!-- START Form Control-->
      <div class="form-group form-group-default">
        <%= f.label :password %>
        <div class="controls">
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password', required: 'required' %>
        </div>
      </div>
      <!-- START Form Control-->
      <div class="row">
        <div class="col-md-6">
          <div class="checkbox ">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me, t('activerecord.attributes.organization.remember_me') %>
          </div>
        </div>
        <!--<div class="col-md-6 text-right">
          <a href="#" class="text-info small">Help? Contact Support</a>
        </div>-->
      </div>
      <!-- END Form Control-->
      <%= f.submit t('login'), class: 'btn btn-primary btn-cons m-t-10' %> <span class="m-r-10 m-l-5"><%= t 'or' %></span>
        <%= link_to t('register'), new_organization_registration_path, class: 'btn btn-success btn-cons m-t-10' %>
    <% end %>

    <%= link_to t('devise.passwords.forgot_your_password'), new_password_path('organization') %><br />
  </div>
</div>

<% content_for :javascripts do %>

    <script>
      $(function() {
        $('#form-login').validate()
      })
    </script>

<% end %>