config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :organizations, controllers: {
      sessions: 'organizations/sessions',
      registrations: 'organizations/registrations'
  }

  root 'welcome#index'

  get '/welcome_organizations' =>'welcome#index_organizations', as: :welcome_organizations

  get '/town-by-province' => 'location#town_by_province', as: :town_by_province
  get '/provinces-by-region' => 'location#provinces_by_region', as: :provinces_by_region
  get '/s/:id' => 'shortener/shortened_urls#show', as: :short_url
  get '/account-locked' => 'welcome#account_locked', as: :account_locked

  post '/tinymce_assets' => 'posts#tinymce_assets_create'
  post '/contact' => 'welcome#contact', as: :contact

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          post '/images', to: 'users#update_images'
        end
        member do
          get :campaigns
          post '/campaigns/:campaign_id', to: 'users#send_campaign'
        end
        member do
          get :organizations
          get '/organizations/:organization_id', to: 'users#show_organization'
          put '/organizations/:organization_id', to: 'users#follow_organization'
        end
        member do
          get :topics
          get '/topics/:topic_id', to: 'users#show_topic'
          put '/topics/:topic_id', to: 'users#follow_topic'
        end
      end
      resources :organizations do
        member do
          get :campaigns
        end
      end
      resources :campaigns
      resources :topics do
        member do
          get :campaigns
          get :organizations
        end
      end
      scope 'leaderboard' do
        get '/' => 'leaderboard#index', as: :leaderboard
      end
    end
  end

  namespace :blog do
    resources :campaigns, only: [:index, :show]
    resources :posts, only: [:index, :show]
  end

  scope 'dashboard' do
    get '/' => 'welcome#dashboard', as: :dashboard
    resources :campaigns, except: [ :destroy ] do
      collection do
        get '/filter' => 'campaigns#filter'
      end
      member do
        match :crop, via: [:get, :post]
        delete :stop
        get :statistics
      end
    end
    scope 'analytics' do
      get '/follow_trending' => 'welcome#follow_trending', as: :follow_trending
      get '/campaigns' => 'analytics#campaigns_analytics', as: :campaigns_analytics
      get '/campaign/:id' => 'analytics#campaign_analytics_async', as: :campaign_analytics_async
      get '/campaigns_async' => 'analytics#campaigns_analytics_async'
      get '/my-organization' => 'analytics#organization_analytics', as: :organization_analytics
    end
  end

  post '/organizations/:id/upload' => 'organizations#upload', as: :organizations_upload
  match '/organizations/:id/crop' => 'organizations#crop', as: :organizations_crop, via: [:post, :patch]

  get '/stop/:id' => 'stop#show', as: :stop_service
  delete '/stop/:id' => 'stop#destroy'
  put '/stop/:id' => 'stop#unblacklist'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  include ActiveModel::Serialization

  belongs_to :organization
  belongs_to :town
  belongs_to :province
  belongs_to :region

  has_many :campaign_client_receivers, :dependent => :delete_all
  has_many :receivers, through: :campaign_client_receivers
  has_many :digits_clients, through: :campaign_client_receivers
  has_many :campaign_addresses
  has_many :campaign_analytics

  has_and_belongs_to_many :topics

  accepts_nested_attributes_for :campaign_addresses, allow_destroy: true

  has_attached_file :photo, styles: {
      normal: '1280x720>',
      mobile: '800x450>',
      mobile_max: '2048x2048>',
  },  default_url: '/images/invalid',
      convert_options: {
          normal: '-gravity center -extent 1280x720',
          mobile: '-gravity center -extent 800x450',
          mobile_max: '-resize 2048x2048'
      }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  crop_attached_file :photo, aspect: '16:9'

  validates :message, presence: true, length: { maximum: 306 }
  validates :organization, presence: true
  validates_presence_of :organization_id, :topics
  validates :expires_at, presence: true
  validate :expiration_date_cannot_be_in_the_past

  scope :not_expired, -> { where('expires_at >= ?', Date.today) }

  # do not return the campaign of "Debugging"
  scope :not_test, -> {where('organization_id != ?', 24 )}

  def expired?
    self.expires_at < Date.today
  end

  def deactivate
    self.update_attribute :expires_at, Date.yesterday
  end

  def expires_at_format
    self.expires_at.strftime '%d/%m/%Y' if self.expires_at.present?
  end

  def created_at_format
    self.created_at.strftime('%d/%m/%Y')
  end

  def expiration_date_cannot_be_in_the_past
    if expires_at.present? && expires_at < Date.today
      errors.add(:expires_at, I18n.t('campaigns.errors.cant_be_in_the_past'))
    end
  end

  def photo_mobile
    URI.join(ActionController::Base.asset_host, self.photo.url(:mobile)).to_s
  end

  def photo_normal
    URI.join(ActionController::Base.asset_host, self.photo.url(:normal)).to_s
  end

  def photo_original
    URI.join(ActionController::Base.asset_host, self.photo.url).to_s
  end

  def photo_mobile_max
    URI.join(ActionController::Base.asset_host, self.photo.url(:mobile_max)).to_s
  end

end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < ApplicationController
  # http_basic_authenticate_with name: Rails.application.secrets[:http_basic][:name], password: Rails.application.secrets[:http_basic][:password]
  before_filter :restrict_access unless Rails.env.development?
  before_filter :set_campaign, only: [:show]
  before_filter :set_user, only: [:index]
  force_ssl unless Rails.env.development?

  respond_to :json

  # GET /campaigns
  def index

    # WHILE only few agencies and campaigns are present in Columba, just return all the campaigns

    # # if user param is not used or the user doesn't follow any topic/organization
    # if @user.nil? or (@user.topics.empty? and @user.organizations.empty?)
    #   @campaigns = Campaign.not_expired
    # else
    #   # campaigns under user followed topic
    #   @topics_campaigns = Campaign.not_expired.includes(:topics).where(topics: { id: @user.topics.select(:topic_id) })
    #   # campaigns of organizations followed by user
    #   @organizations_campaigns = Campaign.not_expired.where(organization_id: @user.organizations)
    #
    #   @campaigns= (@topics_campaigns + @organizations_campaigns).uniq
    #   if @campaigns.empty?
    #     # if no active campaign match the user's preferences all the campaigns are returned
    #     # ALESSIO: maybe in this case we should notify the user about it
    #     @campaigns = Campaign.not_expired
    #   end
    # end

    @campaigns = Campaign.not_expired
    if params[:order_field].present? and params[:order_type].present?
      @campaigns = @campaigns.order("#{params[:order_field]}": :"#{params[:order_type]}")
    end

    @campaigns = @campaigns.limit(params[:limit]) if params[:limit].present?

    @campaigns = @campaigns.offset(params[:offset]) if params[:offset].present?

    render json: @campaigns, root: nil
  end

  # GET /campaigns/:id
  def show
    render json: @campaign, root: false
  end

  private

  def set_campaign
    begin
      @campaign = Campaign.find params[:id]
    rescue ActiveRecord::RecordNotFound
      render json: { errors: 'Campaign not found' }
    end
  end

  def set_user
    if params[:user_id].nil?
      @user = nil
    else
      begin
        @user = DigitsClient.find params[:user_id]
      rescue ActiveRecord::RecordNotFound
        render json: { errors: 'User not found' }
      end
    end
  end

  def restrict_access
    head :unauthorized unless DigitsClient.find_by_auth_token(request.headers['X-Auth-Token'])
  end

end

app/controllers/blog/campaigns_controller.rb
class Blog::CampaignsController < ApplicationController
  force_ssl unless Rails.env.development?
  protect_from_forgery except: [:tinymce_assets_create]
  before_filter :set_campaign, only: [:show]
  layout 'application_frontend'

  def index
    @campaigns = Campaign.not_test

    if params[:running].present?
      if params[:running]=="true"
        @campaigns=@campaigns.where('expires_at >= ?', Date.today)
      end
    end

    if params[:organization].present?
      @campaigns = @campaigns.where(organization_id: params[:organization])
      @organization = Organization.find(params[:organization])
    end

    if params[:topic].present?
      @campaigns = @campaigns.includes(:topics).where(topics: { id: params[:topic] })
      @topic = Topic.find params[:topic]
    end

    @campaigns = @campaigns.paginate(page: params[:page], per_page: 5).order('campaigns.created_at DESC')
  end

  def show
  end

  private

  def set_campaign
    @campaign = Campaign.find params[:id]
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_organization!
  before_action :set_campaign, only: [:show, :edit, :update, :crop, :stop, :statistics]
  before_action :validate_visibility
  layout 'application_dashboard'

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = current_organization.campaigns
    render :index
  end

  def filter
    @campaigns = current_organization.campaigns
    count = @campaigns.length
    @campaigns = @campaigns.limit 5

    render json: {
        draw: params[:draw].to_i,
        recordsTotal: count,
        recordsFiltered: @campaigns.count,
        data: @campaigns
    }, root: false
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/{id}/edit
  def edit
  end

  # PUT /campaigns/{id}
  def update
    respond_to do |f|
      if @campaign.update(campaign_params)
        # Spam check
        begin
          Rails.logger.info "SPAM_SCORE:"+SpamController.new.check_spam_score(@campaign.message)
        rescue
          Rails.logger.info "SPAM_SCORE: spam service error"
        end

        f.html { redirect_to @campaign, notice: t('campaigns.edited') }
        f.json { render json: @campaign, root: false }
      else
        f.html { render 'edit' }
        f.json { render json: @campaign.errors, root: false }
      end
    end
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.organization = current_organization
    date = Date.strptime campaign_params[:expires_at], '%d/%m/%Y'
    @campaign.expires_at = date if date.present?

    # Spam check
    begin
      Rails.logger.info "SPAM_SCORE:"+SpamController.new.check_spam_score(@campaign.message)
    rescue
      Rails.logger.info "SPAM_SCORE: spam service error"
    end

    respond_to do |format|
      if @campaign.save

        if DigitsClient.exists?
          gcm = GCM.new(Rails.application.secrets[:gcm_api_key])

          options = {
              data: {
                  organization_name: current_organization.organization_name,
                  avatar_normal: current_organization.avatar_normal,
                  message: @campaign.message,
                  campaign_id: @campaign.id
              }
          }
          response = gcm.send_with_notification_key "/topics/organization_#{current_organization.id}", options
          Rails.logger.info response
        end

        format.html { redirect_to @campaign, notice: I18n.t('campaigns.created') }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET|POST /campaigns/:id/crop
  def crop

  end

  # DELETE /campaigns/:id/stop
  def stop
    if @campaign.deactivate
      flash[:notice] = t('campaigns.deactivated')
    else
      flash[:danger] = t('campaigns.error')
    end
    redirect_to :back
  end

  def statistics
    campaign_analytic_today = @campaign.campaign_analytics.last
    @data = {}
    if campaign_analytic_today.present?
      @data[:supporters] = campaign_analytic_today.supporters
      @data[:sent_sms] = campaign_analytic_today.sent_sms
    else
      @data[:supporters] = 0
      @data[:sent_sms] = 0
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      begin
        @campaign = Campaign.find(params[:id])

        #   checks if the requested campaign belongs to the current organization
        if current_organization.campaigns.include?(Campaign.find(params[:id]))==false
          # head :unauthorized
          render json: { errors: 'Not your campaign' }, status: :unauthorized
        end
      rescue ActiveRecord::RecordNotFound
        render json: { errors: 'Campaign not found' }, status: :not_found
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params[:campaign].permit(:message, :region_id, :province_id, :town_id, :expires_at,
                               :long_description, :photo,
                               :topic_ids => [], :campaign_address_ids => [],
                               :campaign_addresses_attributes => [:id, :address, :_destroy])
    end

    def validate_visibility
      unless current_organization.visible
        redirect_to dashboard_path, notice: I18n.t('campaigns.update_account')
      end
    end
end

app/helpers/api/v1/campaigns_helper.rb
module Api::V1::CampaignsHelper
end

app/helpers/blog/campaigns_helper.rb
module Blog::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign_address_fields.html.erb
<div class="nested-fields m-t-10">
  <div class="field form-group form-group-default required">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control geocode' %>
  </div>
  <%= link_to_remove_association t('campaigns.addresses.remove_address'), f,
                                 class: 'btn btn-primary btn-cons' %>
</div>

app/views/campaigns/_form.html.erb
<% content_for :head_js do %>
    <!--suppress ALL -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAMeEfCTnpsPhSqICGC5e7QEIhzCpYjazg&libraries=places"
            async defer></script>
<% end %>

<%= form_for(@campaign, html: { role: 'form', id: 'new-campaign' }) do |f| %>
  <% if @campaign.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@campaign.errors.count, t('error'), t('errors')) %> <%= t 'campaigns.prohibited' %></h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-group-default required">
    <%= f.label :message %>
    <%= f.text_field :message, class: 'form-control full-height', rows: '10', required: 'required', maxlength: '306' %>
    <em id="message_length"></em>
  </div>

  <div class="form-group form-group-default">
    <%= f.label :long_description, nil, style: 'margin-bottom: 5px;' %>
    <%= f.text_area :long_description, class: 'wysiwyg form-control full-width', style: 'height: 250px' %>
  </div>

    <div class="form-group form-group-default">
      <%= f.label :photo %>
      <%= image_tag @campaign.photo.url(:normal), width: 800, height: 450, class: 'm-b-10' unless @campaign.new_record? or not @campaign.photo.exists? %>
      <div class="clearfix"></div>
      <button id="upload_photo" class="btn btn-primary btn-cons m-b-5"><%= t 'campaigns.upload_photo' %></button>
      <%= f.file_field :photo, id: 'photo_input', style: 'display: none;' %>
      <span id="photo_text"><%= @campaign.photo_file_name unless @campaign.new_record? %></span>
    </div>

  <div class="form-group form-group-default form-group-default-select2 required">
    <label for="topic_ids"><%= t 'campaigns.topics' %></label>
    <%= f.select :topic_ids, current_organization.topics.collect { |x| [x.name, x.id] }, { }, { multiple: true, 'data-init-plugin': 'select2', class: 'full-width' } %>
  </div>

  <div class="form-group form-group-default required">
    <label for="expires_at"><%= t 'campaigns.expiration_date' %></label>
    <%= f.text_field :expires_at, value: @campaign.new_record? ? '' : @campaign.expires_at.strftime('%d/%m/%Y'), class: 'form-control', id: 'datepicker', required: 'required' %>
  </div>

  <div class="row" style="margin-left: 0; margin-right: 0;">
    <div class="col-sm-12 col-md-12">
        <em><%= t 'campaigns.date_explanation' %></em>
    </div>
  </div>

    <div class="row m-t-10" style="margin-left: 0; margin-right: 0;">
      <div class="col-sm-12 col-md-4">
        <div class="form-group form-group-default form-group-default-select2">
          <label for="region_id"><%= t 'region' %></label>
          <%= f.select :region_id, Region.order(name: :asc).all.collect { |r| [r.name, r.id] }.push(['', '']),
                       { selected: (@campaign.new_record? or @campaign.region.nil?) ? '' : @campaign.region_id },
                       { 'data-init-plugin': 'select2', class: 'full-width', id: 'region-select' } %>
        </div>
      </div>

      <div class="col-sm-12 col-md-4">
        <div class="form-group form-group-default form-group-default-select2">
          <label for="province_id"><%= t 'province' %></label>
          <%= f.hidden_field :province_id, class: 'full-width', id: 'province-select'  %>
        </div>
      </div>

      <div class="col-sm-12 col-md-4">
        <div class="form-group form-group-default form-group-default-select2 full-width">
          <label for="town_id"><%= t 'town' %></label>
          <%= f.hidden_field :town_id, class: 'full-width', id: 'town-select'  %>
        </div>
      </div>
    </div>

    <div class="panel-heading" style="padding-left: 0;">
      <div class="panel-title full-width" style="color: #333;">
        <span class="pull-left"><%= t 'addresses' %></span>

      </div>
    </div>

    <div class="row m-t-10" style="margin-left: 0; margin-right: 0;">
      <div class="col-sm-12 col-md-12" id="addresses">
        <%= f.fields_for :campaign_addresses do |ff| %>
            <%= render 'campaign_address_fields', f: ff %>
        <% end %>
        <%= link_to_add_association t('campaigns.addresses.add_address'),
                                    f, :campaign_addresses,
                                    class: 'btn btn-primary btn-cons pull-right',
                                    style: 'color: #fff' %>
      </div>
    </div>

    <%= f.submit t('send'), class: 'btn btn-primary btn-cons m-t-10 full-width' %>
<% end %>

<% content_for :javascripts do %>

    <script>
      $('#new-campaign').validate();

      var provinceData = [{ id: '', text: '' }];
      <% if @campaign.region.present? %>
        provinceData = <%= raw @campaign.region.provinces.order(name: :asc).all.collect { |r| { text: r.name, id: r.id } }.push({ text: '', id: '' }).to_json %>;
      <% end %>

      var townData = [{ id: '', text: '' }];
      <% if @campaign.province.present? %>
        townData = <%= raw @campaign.province.towns.order(name: :asc).all.collect { |r| { text: r.name, id: r.id } }.push({ text: '', id: '' }).to_json %>;
      <% end %>

      $('#province-select').select2({
        data: provinceData
      });
      $('#town-select').select2({
        data: townData
      });

      $('#region-select').on('change', function() {
        sendLocation('region', $(this).val(), $('#province-select'), $('#town-select'));
      });

      $('#province-select').on('change', function() {
        sendLocation('province', $(this).val(), $('#town-select'), null);
      });

      $('#upload_photo').click(function(e) {
        e.preventDefault();
        $('#photo_input').click();
      });

      $('#photo_input').change(function() {
        var fileName = $(this).val().match(/[^\/\\]+$/);
        $('#photo_text').html(fileName);
      });

      $('#addresses').on('cocoon:after-insert', function(e, added_task) {
        var autocomplete = new google.maps.places.Autocomplete(
            added_task.find('input').get(0), { types: ['geocode'] }
        );
      });

      function computeLength() {
        var message = $('#campaign_message').val();
        if (message != null && typeof message !== 'undefined') {
          $('#message_length').html(message.length + ' / 306');
        } else {
          $('#message_length').html('0 / 306');
        }
      }

      computeLength();
      $('#campaign_message').keyup(function() {
        computeLength();
      });

      function sendLocation(type, value, $elem, $nullElement) {
        var url = '';
        switch (type) {
          case 'region':
                url = '/provinces-by-region';
                break;
          case 'province':
                url = '/town-by-province';
                break;
          default:
                url = '/town-by-province';
                break;
        }
        var data = {};
        data[type + '_id'] = value;
        data['first'] = false;
        $.ajax({
          url: url,
          data: data,
          success: function(data) {
            $elem.select2({
              data: data.data
            }).select2('val', data.selected);
            if ($nullElement != null) {
              $nullElement.select2({
                data: [{ id: '', text: '' }]
              });
            }
          }
        })
      }
    </script>

<% end %>

app/views/campaigns/edit.html.erb
<% title t('campaigns.edit_title') %>

<% content_for :application_js do %>
    <%= javascript_include_tag('application_form', 'data-turbolinks-track' => true) %>
<% end %>

<% content_for :application_css do %>
    <%= stylesheet_link_tag('application_form', 'data-turbolinks-track' => true) %>
<% end %>

<div class="col-md-12 col-center">
  <div class="panel panel-default">

    <div class="panel-heading">
      <div class="panel-title">
        <%= t 'campaigns.edit_campaign' %>
      </div>
    </div>

    <div class="panel-body">
      <h5><%= t 'campaigns.update' %></h5>

      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/campaigns/index.html.erb
<% title t('campaigns.index_title') %>

<% content_for :application_js do %>
    <%= javascript_include_tag('application_data', 'data-turbolinks-track' => true) %>
<% end %>

<% content_for :application_css do %>
    <%= stylesheet_link_tag('application_data', 'data-turbolinks-track' => true) %>
<% end %>

<div class="container-fluid container-fixed-lg bg-white">

  <div class="panel panel-transparent">
    <div class="panel-heading">
      <div class="panel-title"><%= t 'campaigns.my_campaigns' %>
      </div>
      <div class="pull-right">
        <div class="col-xs-12">
          <input type="text" id="search-table" class="form-control pull-right" placeholder="Search">
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="panel-body">

      <table id="campaigns-table" class="table table-hover" cellspacing="0" width="100%">

        <thead>
        <tr>
          <th><%= t 'campaigns.message' %></th>
          <th><%= t 'campaigns.date_created' %></th>
          <th><%= t 'campaigns.topics' %></th>
          <th><%= t 'campaigns.expiration_date' %></th>
          <th><%= t 'campaigns.actions' %></th>
        </tr>
        </thead>

        <tbody>
        <% @campaigns.each do |campaign| %>
            <tr>
              <td class="v-align-middle"><%= campaign.message %></td>
              <td class="v-align-middle"><%= campaign.created_at.strftime("%B %-d, %Y %H:%M") %></td>
              <td class="v-align-middle">
                <% campaign.topics.each do |topic| %>
                    <a href="javascript:;" class="btn btn-tag"><%= topic.name %></a>
                <% end %>
              </td>
              <td class="v-align-middle"><%= campaign.expires_at_format %></td>
              <td class="v-align-middle" style="width: 30%;">
                <%= link_to t('campaigns.show'), campaign %> |
                <%= link_to t('campaigns.edit'), edit_campaign_path(campaign) %> |
                <%= link_to t('menu.statistics'), statistics_campaign_path(campaign) %>
                <% unless campaign.expired? %>
                 | <%= link_to t('campaigns.stop'), stop_campaign_path(campaign), method: :delete %>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>

      </table>

    </div>
  </div>

</div>

<% content_for :javascripts do %>

  <script>
    $(function() {

      var responsiveHelper = undefined;
      var breakpointDefinition = {
        tablet: 1024,
        phone: 480
      };

      var table = $('#campaigns-table');

      var settings = {
        "sDom": "<'table-responsive't><'row'<p i>>",
        "destroy": true,
        "scrollCollapse": true,
        "oLanguage": {
          "sLengthMenu": "_MENU_ ",
          "sInfo": "<%= raw t('datatable') %>"
        },
        "iDisplayLength": 5,
        "order": [[3, "desc"]]
      };

      table.dataTable(settings);

      // search box for table
      $('#search-table').keyup(function() {
        table.fnFilter($(this).val());
      });

    });
  </script>

<% end %>

app/views/campaigns/new.html.erb
<% title t('campaigns.new_title') %>

<% content_for :application_js do %>
    <%= javascript_include_tag('application_form', 'data-turbolinks-track' => true) %>
<% end %>

<% content_for :application_css do %>
    <%= stylesheet_link_tag('application_form', 'data-turbolinks-track' => true) %>
<% end %>

<div class="col-md-12 col-center">
  <div class="panel panel-default">

    <div class="panel-heading">
      <div class="panel-title">
        <%= t 'campaigns.new_campaign' %>
      </div>
    </div>

    <div class="panel-body">
      <h5><%= t 'campaigns.create' %></h5>

      <%= render 'form' %>
    </div>

  </div>
</div>

app/views/campaigns/show.html.erb
<% title @campaign.message %>

<div class="col-md-12 col-center">
  <div class="panel panel-default">

    <div class="panel-body">
      <% if @campaign.photo.exists? %>
        <div style="max-height: 300px;" class="full-width m-b-10">
          <div style="height: 300px; max-height: 300px; display: block; margin: 0 auto;">
            <%= image_tag @campaign.photo.url(:normal), class: 'img-responsive', style: 'max-height: 300px; margin: 0 auto;' %>
          </div>
        </div>
      <% end %>
      <table class="table full-width campaign-single">
        <tr>
          <td><strong><%= t('campaigns.message') %>:</strong></td>
          <td><%= @campaign.message %></td>
        </tr>
        <tr>
          <td><strong><%= t('activerecord.attributes.campaign.long_description') %>:</strong></td>
          <td><%= raw @campaign.long_description %></td>
        </tr>
        <tr>
          <td><strong><%= t('campaigns.topics') %>:</strong></td>
          <td><%= @campaign.topics.collect { |t| t.name }.join(', ') %></td>
        </tr>
        <tr>
          <td><strong><%= t('campaigns.expiration_date') %>:</strong></td>
          <td><%= @campaign.expires_at.strftime('%d/%m/%Y') %></td>
        </tr>
        <tr>
          <td><strong><%= t('region') %>:</strong></td>
          <td><%= @campaign.region if @campaign.region.present? %></td>
        </tr>
        <tr>
          <td><strong><%= t('province') %>:</strong></td>
          <td><%= @campaign.province if @campaign.province.present? %></td>
        </tr>
        <tr>
          <td><strong><%= t('town') %>:</strong></td>
          <td><%= @campaign.town if @campaign.town.present? %></td>
        </tr>
        <tr>
          <td><strong><%= t('addresses') %>:</strong></td>
          <td><%= raw @campaign.campaign_addresses.collect { |c| c.address }.join('<br />') if @campaign.campaign_addresses.present? %></td>
        </tr>
      </table>
      <%= link_to t('campaigns.edit'), edit_campaign_path(@campaign), class: 'btn btn-primary btn-cons' %>
      <%= link_to t('menu.statistics'), statistics_campaign_path(@campaign), class: 'btn btn-primary btn-cons' %>
    </div>

  </div>
</div>