config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :organizations, controllers: {
      sessions: 'organizations/sessions',
      registrations: 'organizations/registrations'
  }

  root 'welcome#index'

  get '/welcome_organizations' =>'welcome#index_organizations', as: :welcome_organizations

  get '/town-by-province' => 'location#town_by_province', as: :town_by_province
  get '/provinces-by-region' => 'location#provinces_by_region', as: :provinces_by_region
  get '/s/:id' => 'shortener/shortened_urls#show', as: :short_url
  get '/account-locked' => 'welcome#account_locked', as: :account_locked

  post '/tinymce_assets' => 'posts#tinymce_assets_create'
  post '/contact' => 'welcome#contact', as: :contact

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          post '/images', to: 'users#update_images'
        end
        member do
          get :campaigns
          post '/campaigns/:campaign_id', to: 'users#send_campaign'
        end
        member do
          get :organizations
          get '/organizations/:organization_id', to: 'users#show_organization'
          put '/organizations/:organization_id', to: 'users#follow_organization'
        end
        member do
          get :topics
          get '/topics/:topic_id', to: 'users#show_topic'
          put '/topics/:topic_id', to: 'users#follow_topic'
        end
      end
      resources :organizations do
        member do
          get :campaigns
        end
      end
      resources :campaigns
      resources :topics do
        member do
          get :campaigns
          get :organizations
        end
      end
      scope 'leaderboard' do
        get '/' => 'leaderboard#index', as: :leaderboard
      end
    end
  end

  namespace :blog do
    resources :campaigns, only: [:index, :show]
    resources :posts, only: [:index, :show]
  end

  scope 'dashboard' do
    get '/' => 'welcome#dashboard', as: :dashboard
    resources :campaigns, except: [ :destroy ] do
      collection do
        get '/filter' => 'campaigns#filter'
      end
      member do
        match :crop, via: [:get, :post]
        delete :stop
        get :statistics
      end
    end
    scope 'analytics' do
      get '/follow_trending' => 'welcome#follow_trending', as: :follow_trending
      get '/campaigns' => 'analytics#campaigns_analytics', as: :campaigns_analytics
      get '/campaign/:id' => 'analytics#campaign_analytics_async', as: :campaign_analytics_async
      get '/campaigns_async' => 'analytics#campaigns_analytics_async'
      get '/my-organization' => 'analytics#organization_analytics', as: :organization_analytics
    end
  end

  post '/organizations/:id/upload' => 'organizations#upload', as: :organizations_upload
  match '/organizations/:id/crop' => 'organizations#crop', as: :organizations_crop, via: [:post, :patch]

  get '/stop/:id' => 'stop#show', as: :stop_service
  delete '/stop/:id' => 'stop#destroy'
  put '/stop/:id' => 'stop#unblacklist'

end

app/views/layouts/_footer_frontend.html.erb
<footer id="footer">
  <figure><img src="<%= asset_path 'logo_257x81_teal.png' %>" alt="Placeholder" width="174" height="55"></figure>
  <h3><%= t 'frontend.follow_us' %></h3>
  <ul class="social-a">
    <li class="fb"><a rel="external" href="https://www.facebook.com/columbasms/">Facebook</a></li>
    <li class="tw"><a rel="external" href="https://twitter.com/ColumbaSms">Twitter</a></li>
    <li class="in"><a rel="external" href="https://www.instagram.com/columbasms/">Instagram</a></li>
  </ul>
  <ul class="download-a">
    <li class="gp"><a rel="external" target="_blank" href="https://play.google.com/store/apps/details?id=com.columbasms.columbasms">Get it on Google Play</a></li>
  </ul>
  <p>&copy; <span class="date">2016</span> Columba SMS. <%= t 'frontent.rights' %>.
</footer>

app/views/layouts/_header.html.erb
<% logo = asset_path('logo_website_dark.png') %>
<% logo2x = asset_path('logo_website_dark_x2.png') %>
<div class="header">

  <!-- START MOBILE CONTROLS -->
  <div class="container-fluid relative">
    <!-- LEFT SIDE -->
    <div class="pull-left full-height visible-sm visible-xs">
      <!-- START ACTION BAR -->
      <div class="header-inner">
        <a href="#" class="btn-link toggle-sidebar visible-sm-inline-block visible-xs-inline-block padding-5" data-toggle="sidebar">
          <span class="icon-set menu-hambuger"></span>
        </a>
      </div>
      <!-- END ACTION BAR -->
    </div>
    <div class="pull-center hidden-md hidden-lg">
      <div class="header-inner">
        <div class="brand inline">
          <img src="<%= logo %>" alt="logo" data-src="<%= logo %>" data-src-retina="<%= logo2x %>" width="78" height="22">
        </div>
      </div>
    </div>
    <!-- RIGHT SIDE -->
    <div class="pull-right visible-sm visible-xs">
      <div class="header-inner">
        <button class="btn-link m-l-20 visible-sm visible-xs" data-toggle="dropdown" data-toggle-element="#language" aria-haspopup="true" aria-expanded="true">
          <span class="thumbnail-wrapper d32 inline m-t-5">
            <%= image_tag "#{I18n.locale}.png", width: 32, height: 32 %>
          </span>
        </button>
        <ul id="language" class="dropdown-menu profile-dropdown" role="menu" style="left: -75px;">
          <li style="padding-bottom: 11px;">
            <a href="javascript:window.location.href = '<%= url_for action: action_name, controller: controller_name, locale: ((I18n.locale.to_s == 'it') ? 'en' : 'it') %>';">
              <span class="d32">
                <%= image_tag "#{((I18n.locale.to_s == 'it') ? 'en' : 'it')}.png", width: 32, height: 32 %>
              </span>
              <span class="m-l-10"><%= t "language.reverse.#{I18n.locale}" %></span>
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="pull-right full-height visible-sm visible-xs">
      <!-- START ACTION BAR -->
      <div class="header-inner dropdown">
        <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="thumbnail-wrapper d32 circular inline m-t-5">
                <img src="<%= current_organization.avatar.url(:thumb) %>" alt="" data-src="<%= current_organization.avatar.url(:thumb) %>" width="32" height="32">
          </span>
        </button>
        <ul class="dropdown-menu profile-dropdown" role="menu">
          <li><a href="<%= url_for edit_organization_registration_path %>"><i class="fa fa-user"></i> <%= t 'profile' %></a>
          </li>
          <li class="bg-master-lighter">
            <%= link_to(destroy_organization_session_path, method: :delete, class: 'clearfix') do %>
                <span class="pull-left"><%= t 'logout' %></span>
                <span class="pull-right"><i class="pg-power"></i></span>
            <% end %>
          </li>
        </ul>
      </div>
      <!-- END ACTION BAR -->
    </div>
  </div>
  <!-- END MOBILE CONTROLS -->

  <div class="pull-left sm-table hidden-xs hidden-sm">
    <div class="header-inner">
      <div class="brand inline">
        <img src="<%= logo %>" alt="logo" data-src="<%= logo %>" data-src-retina="<%= logo2x %>" width="78" height="22">
      </div>
    </div>
  </div>

  <div class="pull-right hidden-xs hidden-sm">
      <div class="m-t-10">
        <button class="btn-link m-l-20 sm-no-margin hidden-sm hidden-xs" data-toggle="dropdown" data-toggle-element="#language" aria-haspopup="true" aria-expanded="true">
          <span class="thumbnail-wrapper d32 inline m-t-5">
            <%= image_tag "#{I18n.locale}.png", width: 32, height: 32 %>
          </span>
        </button>
        <ul id="language" class="dropdown-menu profile-dropdown" role="menu" style="left: -75px;">
          <li style="padding-bottom: 11px;">
            <a href="javascript:window.location.href = '<%= url_for action: action_name, controller: controller_name, locale: ((I18n.locale.to_s == 'it') ? 'en' : 'it') %>';">
              <span class="d32">
                <%= image_tag "#{((I18n.locale.to_s == 'it') ? 'en' : 'it')}.png", width: 32, height: 32 %>
              </span>
              <span class="m-l-10"><%= t "language.reverse.#{I18n.locale}" %></span>
            </a>
          </li>
        </ul>
      </div>
  </div>

  <div class=" pull-right">
    <!-- START User Info-->
    <div class="visible-lg visible-md m-t-10">
      <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
        <%= current_organization.organization_name %>
      </div>
      <div class="dropdown pull-right">
        <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="thumbnail-wrapper d32 circular inline m-t-5">
                <img src="<%= current_organization.avatar.url(:thumb) %>" alt="" data-src="<%= current_organization.avatar.url(:thumb) %>" width="32" height="32">
            </span>
        </button>
        <ul class="dropdown-menu profile-dropdown" role="menu">
          <li><a href="<%= url_for edit_organization_registration_path %>"><i class="fa fa-user"></i> <%= t 'profile' %></a>
          </li>
          <li class="bg-master-lighter">
            <%= link_to(destroy_organization_session_path, method: :delete, class: 'clearfix') do %>
              <span class="pull-left"><%= t 'logout' %></span>
              <span class="pull-right"><i class="pg-power"></i></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <!-- END User Info-->
  </div>

</div>

app/views/layouts/_header_frontend.html.erb
<header id="top">
  <h1><a href="/"><img src="<%= image_path 'logo_257x81_white.png' %>" alt="Placeholder" width="257" height="81"></a></h1>
  <nav id="nav">
    <ul>
      <!--HOME-->
      <li><%= link_to 'Home', root_path %></li>

      <!--PROJECT-->
      <% if controller_name != 'campaigns'%>
          <li class="sub">
            <a href="javascript:windowScrollTo('content')"><%= t 'frontend.the_project' %></a>
            <ul>
              <!--<li><a href="#">La Storia</a></li>-->
              <li><a href="javascript:windowScrollTo('team');"><%= t 'frontend.who_we_are' %></a></li>
              <li><a href="javascript:windowScrollTo('contact');"><%= t 'frontend.contact' %></a></li>
            </ul>
          </li>
      <% end %>

      <!--APP: index SCROLL-->
      <% if controller_name == 'welcome' and action_name == 'index' %>
          <!--<li><a href="javascript:windowScrollTo('content')">APP</a></li>-->
          <li><a href="javascript:windowScrollTo('media')">MEDIA</a></li>
      <% end %>

      <!--ONLUS index SCROLL -->
      <% if controller_name == 'welcome' and action_name == 'index_organizations' %>
          <!--<li><a href="javascript:windowScrollTo('content')"><%= t 'frontend_organizations.motivations' %></a></li>-->
      <% end %>

      <!--PARTNERS-->
      <% if controller_name != 'campaigns'%>
          <li><a href="javascript:windowScrollTo('partners')"><%= t 'frontend.partners' %></a></li>
      <% end %>


      <!--BLOG-->
      <!--<li><!%= link_to 'Blog', blog_posts_path %></li>-->

      <!--ONLUS: blog of Campaigns-->
      <li><%= link_to t('campaigns.campaigns'), blog_campaigns_path %></li>

      <!--ONLUS, login/dashboard-->
      <li class="sub">
        <%= link_to 'ONLUS', welcome_organizations_path %>
        <ul>
          <li>
            <% if organization_signed_in? %>
                <%= link_to 'Dashboard', dashboard_path %>
            <% else %>
                <%= link_to t('frontend.login_for_organizations'), new_organization_session_path %>
                <%= link_to t('register'), new_organization_registration_path %>
            <% end %>
          </li>
        </ul>
      </li>

      <!--LANGUAGE-->
      <li class="sub">
        <a accesskey="2"><%= image_tag "#{I18n.locale.to_s}.png", width: 32, height: 32 %></a> <em>(2)</em>
        <ul>
          <li style="padding-bottom: 11px;">
            <a href="javascript:window.location.href = '<%= url_for action: action_name, controller: controller_name, locale: ((I18n.locale.to_s == 'it') ? 'en' : 'it') %>';">
              <span class="d32">
                <%= image_tag "#{((I18n.locale.to_s == 'it') ? 'en' : 'it')}.png", width: 32, height: 32 %>
              </span>
              <span class="m-l-10"><%= t "language.reverse.#{I18n.locale}" %></span>
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="page-sidebar" data-pages="sidebar">

  <div class="sidebar-header">
    <img src="<%= image_path 'logo_website_white.png' %>" alt="logo" class="brand" data-src="<%= image_path 'logo_website_white.png' %>" data-src-retina="<%= image_path 'logo_website_white_x2.png' %>" width="78" height="22">
    <div class="sidebar-header-controls">
      <button data-toggle-pin="sidebar" class="btn btn-link visible-lg-inline" type="button"><i class="fa fs-12"></i>
      </button>
    </div>
  </div>

  <div class="sidebar-menu">

    <%= render_navigation %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic %>
  <title><%= yield(:title).presence || 'Columba' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="theme-color" content="#009688">
  <meta content="" name="description" />
  <meta content="" name="author" />

  <%= yield :head_js %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!--[if lte IE 9]>
    <%= stylesheet_link_tag 'ie9', media: 'all', 'data-turbolinks-track' => true %>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
  <script type="text/javascript">
    window.onload = function()
    {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<%= stylesheet_link_tag 'windows.chrome.fix', 'data-turbolinks-track' => true %>'
    }
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74341764-1', 'auto');
    ga('send', 'pageview');

  </script>
  <%= csrf_meta_tags %>
</head>
<body class="fixed-header sidebar-visible menu-pin">

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :javascripts %>
</body>
</html>

app/views/layouts/application_dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).presence || 'Columba' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="theme-color" content="#009688">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <%= yield(:application_css).presence || stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
  <%= yield :stylesheets %>
  <!--[if lte IE 9]>
    <%= stylesheet_link_tag 'ie9', media: 'all', 'data-turbolinks-track' => true %>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
  <script type="text/javascript">
    window.onload = function()
    {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<%= stylesheet_link_tag 'windows.chrome.fix', 'data-turbolinks-track' => true %>'
    }
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74341764-1', 'auto');
    ga('send', 'pageview');

  </script>
  <%= yield :head_js %>
  <%= csrf_meta_tags %>
</head>
<body class="fixed-header sidebar-visible menu-pin">

<%= render partial: 'layouts/sidebar' %>

<div class="page-container">
  <%= render partial: 'layouts/header' %>

  <% unless controller_name == 'registrations' and (action_name == 'edit' or action_name == 'update') %>
    <div class="page-content-wrapper ">
      <div class="content sm-gutter">
        <div class="container-fluid padding-25 sm-padding-10">

          <% if flash[:notice].present? %>
            <div class="alert alert-info alert-dismissable m-b-15 p-15">
              <button type="button" class="close m-r-15" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= flash[:notice] %>
            </div>
          <% end %>

          <% if flash[:danger].present? %>
              <div class="alert alert-danger alert-dismissable m-b-15 p-15">
                <button type="button" class="close m-r-15" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= flash[:danger] %>
              </div>
          <% end %>

          <%= yield %>

        </div>
      </div>
    </div>
  <% else %>
    <div class="page-content-wrapper ">
      <div class="content ">
        <div class="social-wrapper">
          <div class="social " data-pages="social">

            <%= yield %>

          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= yield(:application_js).presence || javascript_include_tag('application', 'data-turbolinks-track' => true) %>
<%= yield :javascripts %>
</body>
</html>

app/views/layouts/application_frontend.html.erb
<!doctype html>
<html class="theme-c has-gradient has-pattern">
  <head>
    <meta charset="utf-8">
    <%= metamagic site: 'Columba',
                  title: [:title, :site], separator: ' - ',
                  og: {
                      site_name: 'Columba SMS',
                      title: 'Columba SMS',
                      type: 'website',
                      description: t('frontend_organizations.project_short'),
                      locale: 'it_IT',
                      :'locale:alternate' => 'en_US',
                      url: request.original_url,
                      image: image_url('cover.png')
                  } %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9, user-scalable=no, target-densitydpi=device-dpi">
    <%= stylesheet_link_tag('frontend/screen', media: 'screen', 'data-turbolinks-track' => true) %>
    <%= stylesheet_link_tag('frontend/print', media: 'print', 'data-turbolinks-track' => true) %>
    <%= stylesheet_link_tag('frontend/custom', media: 'screen', 'data-turbolinks-track' => true) %>
    <%= javascript_include_tag('frontend/head', 'data-turbolinks-track' => true) %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <div id="root">

      <%= render partial: 'layouts/header_frontend' %>

      <%= yield %>

      <%= render partial: 'layouts/footer_frontend' %>

    </div>
    <script>
      head.load('<%= asset_path 'application_frontend.js' %>');
    </script>
  </body>
</html>

app/views/layouts/application_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).presence || 'Columba' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="theme-color" content="#009688">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <%= yield(:application_css).presence || stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
  <!--[if lte IE 9]>
    <%= stylesheet_link_tag 'ie9', 'data-turbolinks-track' => true %>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
  <script type="text/javascript">
    window.onload = function() {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<%= stylesheet_link_tag 'windows.chrome.fix', 'data-turbolinks-track' => true %>'
    }
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74341764-1', 'auto');
    ga('send', 'pageview');

  </script>
  <%= csrf_meta_tags %>
</head>
<body class="fixed-header">
  <div class="login-wrapper">

    <%= yield %>

  </div>

  <%= yield(:application_js).presence || javascript_include_tag('login', 'data-turbolinks-track' => true) %>
  <%= yield :javascripts %>
</body>
</html>

app/views/layouts/application_login_no_content.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title><%= yield(:title).presence || 'Columba' %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="theme-color" content="#009688">
  <meta content="" name="description" />
  <meta content="" name="author" />
  <%= yield :head_js %>
  <%= yield(:application_css).presence || stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
  <!--[if lte IE 9]>
    <%= stylesheet_link_tag 'ie9', media: 'all', 'data-turbolinks-track' => true %>
  <![endif]-->
  <%= favicon_link_tag 'favicon.ico' %>
  <script type="text/javascript">
    window.onload = function()
    {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<%= stylesheet_link_tag 'windows.chrome.fix', 'data-turbolinks-track' => true %>'
    }
  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-74341764-1', 'auto');
    ga('send', 'pageview');

  </script>

</head>
<body class="fixed-header">

  <div class="register-container full-height sm-p-t-30">
    <div class="container-sm-height full-height">
      <div class="row row-sm-height">
        <div class="col-sm-12 col-sm-height col-middle <% if action_name == 'account_locked' %>text-center<% end %>">
          <!--<img src="<%= image_path 'logo' %>" alt="logo" data-src="{{ asset('img/logo.png') }}" data-src-retina="{{ asset('img/logo_2x.png') }}" width="78" height="22">-->
          <% if action_name != 'account_locked' %>
            <h3><%= yield(:h3).presence || t('login') %></h3>
          <% end %>

          <% if flash[:error] %>
            <div class="alert alert-danger">
              <%= flash[:error] %>
            </div>
          <% end %>

          <%= yield %>

        </div>
      </div>
    </div>
  </div>

  <%= yield(:application_js).presence || javascript_include_tag('login', 'data-turbolinks-track' => true) %>
  <%= yield :javascripts %>

</body>
</html>